### ISSUE TITLE
Robot position is not updated correctly

### ISSUE THREAD

**Issue by mthiop** [01rfcberlin/robocup-blockly#55]
![grafik](https://user-images.githubusercontent.com/1834623/115401233-79a1d400-a1ea-11eb-8e6b-3e5566490ddf.png)![grafik](https://user-images.githubusercontent.com/1834623/115402196-7bb86280-a1eb-11eb-8630-28902194c5ba.png)

It looks like writing back the position takes too long. This leads to unwanted behavior with the ball. The ball is not dribbled correctly in each step.

**Comment by mthiop** [comment]
"task6": {
            "optimal_blocks": 4,
            "own_robot": {
                "position": {
                    "x": 150,
                    "y": 220,
                    "rotation": 90
                }
            },
            "ball": {
                "position": {
                    "x": 150,
                    "y": 220
                }
            }
        },

case ActionName.Ball.BallKick:
executes maybe sometimes before or after moving to the next cell.

**Comment by schra** [comment]
This can also be reproduced differently:

1. Use https://github.com/MaikePaetzel/robocup-blockly-demo/commit/d617affafcf088aedfbf8f5309168dc4433c07ee
2. In `nextToBall` in `blocklyFunctions`, use `return robotListLeftRef.current[0].isBallKickable;` instead of `return robotListLeftRef.current[0].isNextToBall;`
3. Go to task 7
4. Run this code:
    ![Screenshot from 2021-04-21 15-22-20](https://user-images.githubusercontent.com/23171985/115560993-690a6000-a2b5-11eb-9301-a3286df9580e.png)

3. Observe that now the robot will not stop anymore
