### ISSUE TITLE
give goal feedback *after* the ball enters goal (not already when the ball is kicked)

### ISSUE THREAD

**Issue by froschy** [01rfcberlin/robocup-blockly#58]

**Comment by MaikePaetzel** [comment]
Can you elaborate on that?

**Comment by froschy** [comment]
What i mean by this: When the ball is kicked in front of the goal, the feedback "Tooor!" is given right after the kick, not after the ball passes the goal line.

**Comment by MaikePaetzel** [comment]
This is solved in a somewhat hacky way for now - the alert is only shown when the ball stopped moving. That works fine, unless you dribble the ball into the goal and then keep dribbling. Then the alert alternates between being shown and not shown (since the ball alternates between moving and not moving). Good enough for now though
