### ISSUE TITLE
8: roboter did not leave playing field when solving the lvl

### ISSUE THREAD

**Issue by froschy** [01rfcberlin/robocup-blockly#61]
![grafik](https://user-images.githubusercontent.com/69001402/115474197-3755b280-a23d-11eb-978d-2a6ca989aabd.png)

**Comment by mthiop** [comment]
The error can be reproduced in Task 3:
![grafik](https://user-images.githubusercontent.com/1834623/115474821-9b2cab00-a23e-11eb-9959-4c1dde3d8faf.png)![grafik](https://user-images.githubusercontent.com/1834623/115474867-b3042f00-a23e-11eb-8b73-07bfee50aacd.png)

Robot x position jumps from 4 to 2 to 1 to 0.
I think the bug is related to #55
